config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  namespace :api, defaults: { format: :json } do
    namespace :v1 do
      resources :bank_accounts, only: [ :index, :show ]
      resources :users, only: [ :index, :show ]
    end
  end

  root to: 'pages#home'
  resources :bank_accounts do
    resources :transactions
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  belongs_to :user
  has_many :transactions

  validates :user_id, presence: true
  validates :account_number, uniqueness: true
end

app/models/transaction.rb
class Transaction < ApplicationRecord
  belongs_to :bank_account

  TRANSACTION_TYPE = ['Withdraw', 'Deposit', 'Transfer', 'Transfer Received']

  validates :bank_account, presence: true
  validates :amount, presence: true, numericality: true
  validates :transaction_type, presence: true, inclusion: { in: TRANSACTION_TYPE}
  if :transaction_type == 'Transfer'
    validates :account_receiver, presence: true
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bank_accounts

  validates :first_name, presence: true
  validates :last_name, presence: true

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/api/v1/bank_accounts_controller.rb
class Api::V1::BankAccountsController < ApplicationController
  def index
    @bank_accounts = BankAccount.all.order('id')
  end

  def show
    @bank_account = BankAccount.find(params[:id])
  end
end

app/controllers/api/v1/users_controller.rb
class Api::V1::UsersController < ApplicationController
  def index
    @users = User.all.order('id')
  end

  def show
    @user = User.find(params[:id])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name])
  end
end

app/controllers/bank_accounts_controller.rb
class BankAccountsController < ApplicationController
  def index
    @bank_accounts = BankAccount.all
    @user = current_user
  
  end

  def show
    @user = current_user
    @bank_account = BankAccount.find(params[:id])
    unless @bank_account.user == current_user
      redirect_to bank_accounts_path
    end
  end

  def new
    @user = current_user
    @bank_account = BankAccount.new
  end

  def create
    @bank_account = BankAccount.new
    @bank_account.user = current_user
    @bank_account.account_number = rand(1..999999).to_s
    if @bank_account.save
      redirect_to bank_account_path(@bank_account.id)
    else
      flash[:notice] = 'Algo deu errado. Tente novamente mais tarde.'
      render :new
    end
  end

  private

  def bank_account_params
    params.require(:bank_account).permit(:user, :account_number)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home

  def home
    @user = current_user
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_bank_account, only: [:index, :new]

  def index
    @transactions = @bank_account.transactions
    if params[:query].present? && params[:query_2].present?
      @my_transactions = @transactions.where(created_at: params[:query].to_time.beginning_of_day...params[:query_2].to_time.end_of_day)
    else
      @transactions
    end
  end

  def new
    @transaction = Transaction.new
  end

  def create
    @bank_account = BankAccount.find(params[:bank_account_id]) 
    @transaction = Transaction.new(transaction_params)
    @transaction.bank_account = @bank_account
    @transaction.account_sender = @bank_account.account_number

    if @transaction.amount != nil
      # ///// DEPOSIT /////
      if @transaction.transaction_type == 'Deposit'
        if @transaction.save
          @bank_account.update!(balance: @bank_account.balance + @transaction.amount)
          redirect_to bank_account_path(@bank_account.id), notice: 'The amount has been credited.'
        else
          flash[:notice] = 'Something went wrong. Try again later.'
          render :new
        end
      # ///// WITHDRAW /////
      elsif @transaction.transaction_type == 'Withdraw'
        if @bank_account.balance >= @transaction.amount
          @transaction.save
          @bank_account.update!(balance: @bank_account.balance - @transaction.amount)
          redirect_to bank_account_path(@bank_account.id), notice: 'The amount has been debited.'
        else
          flash[:notice] = "You don't have enough balance for this transaction."
          render :new
        end
      # ///// TRANSFER /////
      elsif @transaction.transaction_type == 'Transfer'

        # ///// TAX /////
        if @transaction.amount > 1000
          tax = 10
        elsif Date.today.on_weekday? && Time.now.hour >= 9 && Time.now.hour < 18
          tax = 5
        else
          tax = 7
        end

        @transf_amount = @transaction.amount + tax

        if @bank_account.balance >= @transf_amount
          @account_receiver = BankAccount.find_by_account_number(@transaction.account_receiver)    
          if @account_receiver != nil && @account_receiver.account_number != @bank_account.account_number
            @transaction.save
            @transaction.account_receiver = @account_receiver.account_number        
            @bank_account.update!(balance: @bank_account.balance - @transf_amount)
            Transaction.create!(amount: @transaction.amount, bank_account_id: @account_receiver.id, transaction_type: 'Transfer Received', account_receiver: @account_receiver.account_number, account_sender: @transaction.account_sender)
            @account_receiver.update!(balance: @account_receiver.balance + @transaction.amount)
            redirect_to bank_account_path(@bank_account.id), notice: 'Transfer successful.'
          elsif @account_receiver != nil && @account_receiver.account_number == @bank_account.account_number
            flash[:notice] = 'You cannot transfer to the same account.'
            render :new
          else
            flash[:notice] = 'This account does not exist or the "Account Number" field has not been filled.'
            render :new
          end
        else
          flash[:notice] = 'Not enough funds.'
          render :new
        end
      else
        flash[:notice] = 'Choose a valid transacton.'
        render :new
      end
    else
      flash[:notice] = 'Put the amount value.'
      render :new
    end

  end

  private

  def set_bank_account
    @bank_account = BankAccount.find(params[:bank_account_id])
  end

  def transaction_params
    params.require(:transaction).permit(:amount, :transaction_type, :bank_account_id, :account_receiver, :account_sender)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bank_accounts/index.html.erb
<div class='skeleton-template'>
  <div class="container">
    <div class="my-card">
      <div class="mb-4 loading skeleton skeleton-title">
        <h1 class=""></h1>
      </div>
      <div class="d-flex justify-content-between">
        <div class="loading skeleton skeleton-subtitle">
          <h2></h2>
        </div>
        <div class="loading skeleton skeleton-button">
          
        </div>
      </div>
      <div class="skeleton skeleton-table">
        <table  class="table table-striped table-bordered mt-3">
          <thead>
            <tr>
              <th scope="col">

              </th>
              <th scope="col">

              </th>
              <th scope="col">

              </th>
            </tr>
          </thead>
          <tbody>
            <% @bank_accounts.each do |bank_account| %>
              <% if bank_account.user == current_user  %>
                <tr>
                  <td>

                  </td>
                  <td class="saldo-table">

                  </td>
                  <td class="text-center">

                  </td>
                </tr>
              <% end %>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="my-card">
    <div class="mb-4">
      <h1 class="">Hello, <%= @user.first_name.capitalize %>!</h1>
    </div>
    <div class="d-flex justify-content-between">
      <div class="">
        <h2>My Accounts</h2>
      </div>
      <div class="">
        <%= link_to "Create Account", new_bank_account_path, class: "button-6" %>
      </div>
    </div>
    <div class=" ">
      <table  class="table table-striped table-bordered mt-3">
        <thead>
          <tr>
            <th scope="col">
              Account Number
            </th>
            <th scope="col">
              Balance
            </th>
            <th scope="col">

            </th>
          </tr>
        </thead>
        <tbody>
          <% @bank_accounts.each do |bank_account| %>
            <% if bank_account.user == current_user  %>
              <tr>
                <td>
                  <%= link_to bank_account_path(bank_account.id), class:"bank-account-link" do %>
                    <%= bank_account.account_number %>
                  <% end %>
                </td>
                <td class="saldo-table">
                  <%= number_to_currency(bank_account.balance, unit: 'R$') %>
                </td>
                <td class="text-center">
                  <%= link_to "See More", bank_account_path(bank_account.id), class: "button-8" %>
                </td>
              </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>
    </div>
  </div>
</div>

app/views/bank_accounts/new.html.erb
<div class="container">
  <div class="row d-flex justify-content-center">
    <div class="my-card col-xs-12 col-sm-6 col-sm-offset-4">
      <%= simple_form_for(@bank_account, :html => { :class => 'form-horizontal items-form', :style => "text-align: left; font-size: 16px; font-family: 'Noto Sans JP', sans-serif; text-decoration: none" }) do |f| %>
        <%= f.button :submit, "Create New Account", class: 'button-7 mb-2'%>
      <%= link_to "Cancel", bank_accounts_path, class: "button-danger"%>
      <% end %>
    </div>
  </div>
</div>

app/views/bank_accounts/show.html.erb
<div class='skeleton-template'>
  <div class="container">
    <div class="my-card">
      <div class="mb-4 loading skeleton skeleton-title">
        <h1 class=""></h1>
      </div>
      <div class="d-flex justify-content-between">
        <div class="loading skeleton skeleton-subtitle">
          <h2></h2>
        </div>
        <div class="loading skeleton skeleton-button">
        </div>
      </div>
      <div class="skeleton skeleton-table">
        <table  class="table table-striped table-bordered mt-3">
          <thead>
            <tr>
              <th scope="col">

              </th>
              <th scope="col">

              </th>
              <th scope="col">

              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
              </td>
              <td >
              </td>
              <td>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="my-card">
    <div class="d-flex justify-content-between">
      <div>
        <h1 class="mb-4">Hello, <%= @user.first_name.capitalize %>!</h1>
        <h4 class="account">Account: <%= @bank_account.account_number %></h4>
      </div>
      <div class="align-self-end">
        <%= link_to "Filter Transaction", bank_account_transactions_path(@bank_account), class: "button-6" %>
        <%= link_to "Make Transaction", new_bank_account_transaction_path(@bank_account.id), class: "button-6 mb-2" %>
        <%= link_to "My Accounts", bank_accounts_path(@bank_account), class: "button-6" %>
      </div>
    </div>
    <hr class="mb-4">
    <div class="d-flex justify-content-between">
      <h2>Balance</h2>
      <span class="saldo"><%= number_to_currency(@bank_account.balance, unit: 'U$') %></span>
    </div>
    <div>
      <table  class="table table-striped table-bordered mt-3">
        <thead>
          <tr>
            <th>Transaction Date</th>
            <th>Transaction Type</th>
            <th>Transaction Amount</th>
            <th>Balance of the Day</th>
          </tr>
        </thead>
        <tbody>
          <% current_balance = 0 %>
          <% @bank_account.transactions.each do |t| %>
            <%
            if t.amount > 1000
              tax = 10
            elsif t.created_at.on_weekday? && t.created_at.hour >= 9 && t.created_at.hour < 18
              tax = 5
            else
              tax = 7
            end
            %>
            <tr>
              <td class="trans-date">
                <%= t.created_at.time.strftime("%d of %B, %Y") %> - <%= t.created_at.time.strftime("%I:%M %p") %>
              </td>
              <td class="trans-type">
                <% if t.transaction_type == 'Transfer Received'%>
                  <%= t.transaction_type %> by <%= t.account_sender %>
                <% elsif t.transaction_type == 'Transfer'%>
                  <%= t.transaction_type %> to <%= t.account_sender %>
                <% else %>
                  <%= t.transaction_type %>
                <% end %>
              </td>
              <td>
                <% if t.transaction_type == 'Deposit'%>
                  <%= number_to_currency(t.amount, unit: '+ U$') %>
                <% elsif t.transaction_type == 'Withdraw'%>
                  <%= number_to_currency(t.amount, unit: '- U$') %>
                <% elsif t.transaction_type == 'Transfer' %>
                  <%= number_to_currency(t.amount, unit: '- (U$') %> + <%= number_to_currency(tax, unit: 'U$') %>(tax))
                <% elsif t.transaction_type == 'Transfer Received' %>
                  <%= number_to_currency(t.amount, unit: '+ U$') %>  
                <% end %>
              </td>
              <td>
                <% if t.transaction_type == 'Deposit' || t.transaction_type == 'Depósito' %>
                  <% current_balance = t.amount + current_balance %>
                  <%= number_to_currency(current_balance, unit: 'U$') %>
                <% elsif t.transaction_type == 'Withdraw'%>
                  <%  current_balance =  current_balance - t.amount %>
                  <%= number_to_currency(current_balance, unit: 'U$') %>
                <% elsif t.transaction_type == 'Transfer' %>
                  <%  current_balance =  current_balance - (t.amount + tax)%>
                  <%= number_to_currency(current_balance, unit: 'U$') %>
                <% elsif t.transaction_type == 'Transfer Received' %>
                  <%  current_balance = t.amount + current_balance %>
                  <%= number_to_currency(current_balance, unit: 'U$') %>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlusBank</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload', defer: true %>
    <meta name="turbolinks-visit-control" content="reload">
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%# <div class='spinner-wrapper'>
      <div class="spinner"></div>
    </div> %>
    <%= yield %>
    <%= render 'shared/flashes' %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="banner" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/background.png);">
  <div class="container">
    <h1>Create your <strong>Online Account</strong>!</h1>
    <p>Sign up now and open your new Online Account.</p>
    <%= link_to "Sign Up", new_user_registration_path, class: "button-10" %>
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon fixed-top mb-4">
  <%= link_to root_path, class: "navbar-brand ml-2" do %>
    <i class="fas fa-comment-dollar"></i>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "My Accounts", bank_accounts_path(@bank_account), class: "nav-link text-light" %>
        </li>
        <li class="nav-item dropdown ml-2 mr-3">
          <%= image_tag "https://cdn.pixabay.com/photo/2015/10/05/22/37/blank-profile-picture-973460_1280.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%= link_to "Create new account", new_bank_account_path, class: "dropdown-item" %>
            <%= link_to "My accounts", bank_accounts_path(@bank_account), class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Log in", new_user_session_path, class: "button-8 mr-2" %>
        </li>
        <li class="nav-item text-info">
          <%= link_to "Sign up", new_user_registration_path, class: "button-9" %>
        </li>
      <% end %>
    </ul>
  </div>
</div>

app/views/transactions/index.html.erb
<div class='skeleton-template'>
  <div class="container">
    <div class="my-card">
      <div class="mb-4 loading skeleton skeleton-title">
        <h1 class=""></h1>
      </div>
      <div class="d-flex justify-content-between">
        <div class="loading skeleton skeleton-subtitle">
          <h2></h2>
        </div>
        <div class="loading skeleton skeleton-button">
          
        </div>
      </div>
      <div class="skeleton skeleton-table">
        <table  class="table table-striped table-bordered mt-3">
          <thead>
            <tr>
              <th scope="col">
              </th>
              <th scope="col">
              </th>
              <th scope="col">
              </th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>
              </td>
              <td class="saldo-table">
              </td>
              <td class="text-center">
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="container">
  <div class="my-card">
    <div class="row d-flex justify-content-center text-center">
      <%= form_tag bank_account_transactions_path(@bank_account), method: :get do %>
        <div class="col">
          <p>Beggining date</p>
          <%= date_field_tag :query,
            params[:query],
            as: :date
          %>
        </div>
        <div class="col">
        <p>End date</p>
        <%= date_field_tag :query_2,
          params[:query_2],
          as: :date
        %>
        </div>
        <%= submit_tag "Search", class: "button-9 my-3" %>
      <% end %>
    </div>
    <div class="d-flex justify-content-between mx-3">
      <h2>Balance</h2>
      <span class="saldo"><%= number_to_currency(@bank_account.balance, unit: 'U$') %></span>
    </div>
    <% if params[:query].present? && params[:query_2].present? %>
      <table  class="table table-striped table-bordered mt-3">
        <tbody>
          <% @my_transactions.each do |t| %>
            <%
            if t.amount > 1000
              tax = 10
            elsif t.created_at.on_weekday? && t.created_at.hour >= 9 && t.created_at.hour < 18
              tax = 5
            else
              tax = 7
            end
            %>
            <tr>
              <td class="trans-date">
                <%= t.created_at.time.strftime("%d of %B, %Y") %> - <%= t.created_at.time.strftime("%I:%M %p") %>
              </td>
              <td class="trans-type">
                <% if t.transaction_type == 'Transfer Received'%>
                  <%= t.transaction_type %> by <%= t.account_sender %>
                <% elsif t.transaction_type == 'Transfer'%>
                  <%= t.transaction_type %> to <%= t.account_sender %>
                <% else %>
                  <%= t.transaction_type %>
                <% end %>
              </td>
              <td>
                <% if t.transaction_type == 'Deposit'%>
                  <%= number_to_currency(t.amount, unit: '+ U$') %>
                <% elsif t.transaction_type == 'Withdraw'%>
                  <%= number_to_currency(t.amount, unit: '- U$') %>
                <% elsif t.transaction_type == 'Transfer' %>
                  <%= number_to_currency(t.amount, unit: '- (U$') %> + <%= number_to_currency(tax, unit: 'U$') %>(tax))
                <% elsif t.transaction_type == 'Transfer Received' %>
                  <%= number_to_currency(t.amount, unit: '+ U$') %>  
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% else %>
      <table  class="table table-striped table-bordered mt-3">
        <tbody>
          <% @transactions.each do |t| %>
            <%
            if t.amount > 1000
              tax = 10
            elsif t.created_at.on_weekday? && t.created_at.hour >= 9 && t.created_at.hour < 18
              tax = 5
            else
              tax = 7
            end
            %>
            <tr>
              <td class="trans-date">
                <%= t.created_at.time.strftime("%d of %B, %Y") %> - <%= t.created_at.time.strftime("%I:%M %p") %>
              </td>
              <td class="trans-type">
                <% if t.transaction_type == 'Transfer Received'%>
                  <%= t.transaction_type %> by <%= t.account_sender %>
                <% elsif t.transaction_type == 'Transfer'%>
                  <%= t.transaction_type %> to <%= t.account_sender %>
                <% else %>
                  <%= t.transaction_type %>
                <% end %>
              </td>
              <td>
                <% if t.transaction_type == 'Deposit'%>
                  <%= number_to_currency(t.amount, unit: '+ U$') %>
                <% elsif t.transaction_type == 'Withdraw'%>
                  <%= number_to_currency(t.amount, unit: '- U$') %>
                <% elsif t.transaction_type == 'Transfer' %>
                  <%= number_to_currency(t.amount, unit: '- (U$') %> + <%= number_to_currency(tax, unit: 'U$') %>(tax))
                <% elsif t.transaction_type == 'Transfer Received' %>
                  <%= number_to_currency(t.amount, unit: '+ U$') %>  
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
    <% end %>
  </div>
</div>

app/views/transactions/new.html.erb
<div class="container">
<div class="row d-flex justify-content-center">
  <div class="my-card col-xs-12 col-sm-6 col-sm-offset-4">
    <%= simple_form_for [@bank_account, @transaction] do |f| %>
      <div class="form-group">
        <div class="">
          <%= f.input :transaction_type, prompt: 'Choose a transaction type', collection:['Withdraw', 'Deposit', 'Transfer'], class: "form-control", label: 'Transaction type', :input_html => {:onchange => "yesnoCheck(this)"}  %>
          <div id="adc" style="display: none;">
          <%= f.input :account_receiver, as: :string, placeholder: 'Account Number', class: "form-control", label:false %>
          </div>
          <%= f.input :amount, as: :decimal, placeholder: 'Amount', class: "form-control", label:false, input_html: { min: '0', step: '0.50'}%>
        </div>
      </div>
      <%= f.button :submit, "Create Transaction", class: 'button-7', style: 'width: 100%'%>
    <% end %>
    <p>Monday to Friday, 9AM to 6PM - <strong>Tax = U$5</strong><br>Other days and times - <strong>Tax = U$7</strong><br>Over U$1000 - <strong>Tax = U$10</strong></p>
  </div>
</div>
</div>

<script>
  function yesnoCheck(that) 
{
    if (that.value == "Transfer") 
    {
        document.getElementById("adc").style.display = "block";
    }
    else
    {
        document.getElementById("adc").style.display = "none";
    }
}
</script>